version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/infra"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/oci"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/gcp"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/portainer"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/portainer-root"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
