# IaC validation filters
iac_workspace_infra:
  - "terraform/infra/**"
  - "terraform/oci/**"
  - "terraform/gcp/**"

iac_workspace_portainer:
  - "terraform/portainer-root/**"
  - "terraform/portainer/**"

iac_ansible:
  - "ansible/**"
  - ".ansible-lint"

iac_stacks_gitlink:
  - "stacks"

iac_tf_infra:
  - "terraform/infra/**"

iac_tf_oci:
  - "terraform/oci/**"

iac_tf_gcp:
  - "terraform/gcp/**"

iac_tf_portainer_root:
  - "terraform/portainer-root/**"

iac_tf_portainer:
  - "terraform/portainer/**"

# Meta pipeline filters
meta_infra:
  - "terraform/infra/**"
  - "terraform/oci/**"
  - "terraform/gcp/**"

meta_ansible:
  - "ansible/**"
  - ".ansible-lint"

meta_portainer:
  - "terraform/portainer/**"
  - "terraform/portainer-root/**"
