# Meta pipeline filters
meta_infra:
  - "terraform/infra/**"
  - "terraform/oci/**"
  - "terraform/gcp/**"

meta_ansible:
  - "ansible/**"
  - ".ansible-lint"

meta_portainer:
  - "terraform/portainer/**"
  - "terraform/portainer-root/**"
