- name: Create partition on block volume
  community.general.parted:
    device: "{{ block_device }}"
    number: 1
    state: present
    fs_type: ext4

- name: Format the partition
  community.general.filesystem:
    fstype: ext4
    dev: "{{ block_device_partition }}"

- name: Mount the volume
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ block_device_partition }}"
    fstype: ext4
    state: mounted

- name: Ensure correct ownership on mount directory
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
