- name: Create {{ service_group }} group
  ansible.builtin.group:
    name: "{{ service_group }}"
    gid: "{{ service_gid }}"
    state: present

- name: Create {{ service_user }} user
  ansible.builtin.user:
    name: "{{ service_user }}"
    uid: "{{ service_uid }}"
    group: "{{ service_group }}"
    state: present
    create_home: no