---
collections:
  - name: community.general    # parted, filesystem modules
    version: "12.4.0"
  - name: ansible.posix         # mount module
    version: "2.1.0"
  - name: community.docker      # docker_network module
    version: "5.0.6"
  - name: cloud.terraform       # terraform_provider inventory plugin
    version: "4.0.0"
